# Generated by Django 2.2 on 2020-10-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
