# Generated by Django 2.2 on 2020-10-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20201022_1043'),
        ('carts', '0007_auto_20201018_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='colors',
            field=models.ManyToManyField(blank=True, to='products.Color'),
        ),
    ]
