# Generated by Django 2.2 on 2020-10-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestemail',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
